# Generated by Django 4.2.1 on 2023-06-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuTable',
            new_name='MenuItem',
        ),
    ]
